### ISSUE TITLE
Doubt on including all classes

### ISSUE THREAD

**Issue by avbinoy** [cyrildewit/repository-pattern-laravel#1]
Great work !!! 
This is not an issue. This is just a query. Anything harm if I include all my classes in the AppServiceProvider.php as I have around 100 classes ? Or is there any better solution ?

**Comment by cyrildewit** [comment]
Hey @avbinoy,

The main reason why I bind repositories to interfaces, is because we can now simply change the underlaying class from an Eloquent implementation to a simple Databse implementation. If you don't want this, you can skip the bindings. Remove the interfaces and just resolve them normally.

I can't find anything about the speed of Laravel's DI, but I think it can handle it. You could a quick benchmark to verify this. You could ask this queston in a Larachat channel.

Or you could think about dropping this pattern, because it's another abstracting level that requires more work. You can sometimes get away with Eloquent model scopes and helper methods.

I hope this information will help you.

Regards,
Cyril

**Comment by avbinoy** [comment]
Thanks for the quick reply. I'm okay with this pattern. I need another abstraction level and want to manage everything in one place. I'm not including the interface code. If you know any other better approach plz send me the links / examples  .
